name: Verify/Examples

permissions:
  contents: read

on:
  workflow_call:


jobs:
  examples:
    runs-on: ubuntu-24.04
    steps:
    - uses: envoyproxy/toolshed/actions/bind-mounts@598eacce15ab5f208102a2fd5669292868002701  # v0.4.0
      with:
        mounts: |
          - src: /mnt/docker
            target: /var/lib/docker
            rm: true
            command-pre: sudo systemctl stop docker
            command-post: sudo systemctl start docker

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
    - run: |
        TEMPDIR=/cache/docker
        sudo mkdir -p "${TEMPDIR}"
        sudo mount -t tmpfs none "$TEMPDIR"
        sudo chown runner "$TEMPDIR"
    - uses: actions/cache/restore@v5
      id: cache
      with:
        path: /cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}
    - run: |
        TEMPDIR=/cache/docker
        sudo mkdir -p /var/lib/docker-examples
        zstd --stdout -d "${TEMPDIR}/docker.tar.zst" | sudo tar --warning=no-timestamp -xf - -C /var/lib/docker-examples
        sudo umount "$TEMPDIR"
      if: steps.cache.outputs.cache-hit == 'true'

    - run: |
        TEMPDIR=/cache/docker
        sudo mkdir -p "${TEMPDIR}"
        sudo mount -t tmpfs none "$TEMPDIR"
        sudo chown runner "$TEMPDIR"
    - uses: actions/cache@v5
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD', '**/*bzl', 'WORKSPACE') }}

    - run: |
        docker pull envoyproxy/envoy:dev
        DEV_CONTAINER_ID=$(docker inspect --format='{{.Id}}' envoyproxy/envoy:dev)
        echo "DEV_CONTAINER_ID=${DEV_CONTAINER_ID}" >> $GITHUB_ENV
    - run: |
        export UID
        echo "common --config=ci" >> repo.bazelrc
        docker compose run --quiet --quiet-pull --quiet-build examples
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_BAKE: true
        BUILDKIT_PROGRESS: quiet

    - run: |
        TEMPDIR=/cache/docker
        sudo tar cf - -C /var/lib/docker-examples . | zstd - -q -T0 -o "${TEMPDIR}/docker.tar.zst"
        ls -alh "${TEMPDIR}/docker.tar.zst"
      if: steps.cache.outputs.cache-hit != 'true' && github.event_name != 'pull_request'
    - uses: actions/cache/save@v5
      if: steps.cache.outputs.cache-hit != 'true' && github.event_name != 'pull_request'
      with:
        path: /cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}
