[package]
name = "example-echo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.0", features = ["full"] }
toolshed-echo = { git = "https://github.com/envoyproxy/toolshed", rev = "c90e42c8379300774680d7c6ae2583a2d967f8ec", subdirectory = "rust/echo" }
